### ISSUE TITLE
Autocompletion Popup Delay Too Long

### ISSUE THREAD

**Issue by mikebronner** [atom/ide-php#10]
Is there a setting to change the delay for autocompletion? It seems to take about 1 second, and I end up waiting for the autocomplete popup content to change after i type, instead of it changing as I type.

(Was able to get the package to work using the work-around with `composer install` mentioned in #6. Would love to see performance of autocomplete improved. Any suggestions? Can I force-index, for example? (I'm wondering if its slow because it might be in the middle of indexing my project, but there is no indicator that anything is happening).

Thanks! :)

**Comment by damieng** [comment]
One thing you can do if you want to delve in behind the scenes is open up dev tools and type this into the console;

`atom.config.set('core.debugLSP', true)`

When you reload you will see all the communication happening between Atom and the PHP language server.

Not sure exactly which delay you are referring to.  Is it how long it takes to decide to present a list (you can force it with ctrl-space) or how long it takes to fill in the screen with the chosen results?

It's also possible we're overloading the language server with spurious autocomplete requests. Typically in atom we would present them continually without context as they were cheap in-memory text comparisons.  Now that they are syntax analyzed and more accurate they're a little more expensive to calculate and can get backed up. On the ide-typescript package we changed it to only start autocomplete when you either press "." or manually trigger it - perhaps some similar sequences would work for PHP if that's the case.

**Comment by harikt** [comment]
@damieng the problem is as you mentioned sometimes the `ctrl+left mouse click` etc doesn't work, may be due to too much overhead on language server. I have noticed if we close the file and try to open again, sometimes things will work as expected.

**Comment by felixfbecker** [comment]
> On the ide-typescript package we changed it to only start autocomplete when you either press "." or manually trigger it

This should look at the value of `InitializationOptions.completionProvider.triggerCharacters`

**Comment by mikebronner** [comment]
Here's a quick screengrab of what I'm experiencing:
![autocomplete-lag](https://user-images.githubusercontent.com/1791050/30388143-9fccd07e-9863-11e7-9afd-3e5d2c52fa82.gif)

Thanks for the debugging suggestions above: I will try them later today. :)

**Comment by damieng** [comment]
Yeah that looks like we're overloading it with previous requests as you type.  

The spec does actually have the triggerCharacters as Felix mentioned - we need to change our provider to actually honor those to keep things snappy.

**Comment by junaidbhura** [comment]
This works really well: https://php-integrator.github.io

Maybe there could be some cues that could be picked up from there?

**Comment by mcharris** [comment]
Ive been doing some debugging and this is definitely overloading it as you type. Is it possible to take advantage of the server setting on the language server to allow multiple connections at once? Im just getting to this so I have about a 5% knowledge on this. 

From what I gather every letter you type it sends the difference to the server for diagnostics. This is the killer. It might be good to allow a 500ms wait time between each letter before sending diagnostics. So that only if the user pauses it would then send it for diagnostics.

**Comment by damieng** [comment]
We have some forthcoming changes in atom-languageclient coming that will massively reduce this by caching the first call results and performing the subsequent filtering client side.

**Comment by harikt** [comment]
one problem with caching is if you open a project A with dependency C, the class C is cached.

Now assume you have a 2nd project with dependency C ( Same as that of first project , eg : we have composer repos now ) then only one dependency file is detected even if you opened and closed the atom editor.

ie only the first one that is cached is taken. We may need some sort of project + folder path based key for hashing.

**Comment by damieng** [comment]
The caching happens per texteditor not per window or even per project and is only for a short duration (when you start typing to when you complete that word)

**Comment by harikt** [comment]
So isn't there some sort of caching happening to the file location / parsing of the files ?
I thought the @felixfbecker server was doing some caching.
I experienced the problem and I am interested to know if that is only happening for me.

**Comment by JasonTheAdams** [comment]
This issue also delays the delivery of snippets. It seems like this autocomplete is checked first, and then snippets provided afterwards.

Perhaps it would be better (if possible) to pass the snippets first, and then load the IDE autocomplete list? That's assuming the IDE list loading is asynchronous.

**Comment by jens1o** [comment]
depends on https://github.com/felixfbecker/php-language-server/pull/451

**Comment by damieng** [comment]
We also have a change coming later today that will only trigger autocomplete on specific characters which should mean that snippets turn up quickly the rest of the time.

**Comment by damieng** [comment]
Everything we can do to our side for this has now been done.
