### ISSUE TITLE
outline order of items

### ISSUE THREAD

**Issue by kklepper** [atom/ide-php#102]
Hello,

I'm new to atom. As far as I can see, the order of the outline items cannot be changed. It seems to be the order found in the original file, which is arbitrary and not significant at all. Therefore, I don't see how this outline could help me navigate in the source code.

A better choice would be an alphabetical order; this way it is easy to find any function by name. Am I missing something?

Of course, if by chance I have the name of the function under my cursor, I can jump to the definition right away by ctrl-mouse-left-button, but for this functionality I don't need the outline either. So to what end the outline has been created?

Regards

**Comment by damieng** [comment]
It was originally in alphabetical order but was changed because more people wanted it in source order.

https://github.com/facebook-atom/atom-ide-ui/issues/37

You can type text into the top of the outline view for filtering.
