### ISSUE TITLE
Language server processes use 99% CPU

### ISSUE THREAD

**Issue by felixkiss** [atom/ide-php#104]
Since yesterday the language-server php processes clog the CPU at 99% constantly. This might be connected to my upgrade to Atom 1.24.0.

```
╭── felix at 🤔  in ~/code
╰─○ ps aux | grep php
felix            73407  99.8  0.8  4485248 135816   ??  R     6:23AM  20:31.23 /usr/local/bin/php felixfbecker/language-server/bin/php-language-server.php --memory-limit=2G
felix            73029  99.8  0.8  4485248 142112   ??  R     6:18AM  25:45.62 /usr/local/bin/php felixfbecker/language-server/bin/php-language-server.php --memory-limit=2G
felix            67726   0.0  0.1  4830336  10532   ??  S     3:02AM   0:05.55 /usr/local/bin/php felixfbecker/language-server/bin/php-language-server.php --memory-limit=2G
```

These processes even continue to run when I quit Atom.app

Any idea what I can try to debug/fix?

**Comment by rsese** [comment]
Are there any Atom processes still running?  And if you kill those language server processes and restart Atom, do you still see the same CPU usage?

**Comment by felixkiss** [comment]
When I quit Atom all  atom processes (Atom, Atom Helper) are gone, but the two php processes running `felixfbecker/language-server` are still running.

If I quit those php processes manually and reopen Atom two new php processes start, again with 99% CPU usage.

**Comment by damieng** [comment]
It sounds like the underlying language server is hanging/looping - that is handled upstream at https://github.com/felixfbecker/php-language-server
