### ISSUE TITLE
Outline and language server appear to be loading infinitely - throws no console notice about mismatched PHP

### ISSUE THREAD

**Issue by pattonwebz** [atom/ide-php#106]
Starting Atom the language server server icon starts to spin to indicate it is loading, it stays like this forever. Opening a `.php` file and the outliner the same loading icon appears and cycles forever - no outline ever appears.

OS is Ubuntu 16.04 LTS with PHP 7.0.

Console threw no error messages or warnings.

My issue was using PHP 7.0. **The fix was to update to PHP 7.1.**

I see that September last year there was a change in the readme to state 7.1 runtime was required however I have been fine (and updating packages) using php 7.0 until just a week or 2 ago. Unsure why it would have working for me if I had unsupported PHP all of this time.

Consider adding some kind of timeout and notice to the console in standard mode too that may be able to indicate a problem and provide a little insight into the cause.

I did not test launching atom in debug mode directly - perhaps an information message would have appeared in the logs to indicate what was up if I had done so.

**Comment by pattonwebz** [comment]
@damieng Thanks for acting quickly on this one, I'm certain that others will benefit from the addition of the new message.

And fixed within 12 hours of reporting? That is an impressive turnaround time. :smiley_cat:

**Comment by damieng** [comment]
Just trying to solve a couple of other small issues before we publish the next release (spurious cancellation errors in the console and some autocomplete priority stuff)

Thanks for the prompt and clear report!

**Comment by pattonwebz** [comment]
No problem on reporting, surprised someone else hadn't reported it before now to be honest - with 7.0 being default in 16.04. Maybe they also didn't run into issues till recently even with older php. 

Anyways looking at the diff report I can see the fix that was added handles the situation that I described perfectly.

Thanks again for maintaining this software, it saves me many hours of scrolling up and down long files haha

**Comment by jens1o** [comment]
cc @felixfbecker
the readme says it's compatible with PHP >= 7.0

**Comment by pelallemant** [comment]
Hi. I'm using `Ubuntu 16.04.4 LTS` and there are no version of PHP7.1 in the official repositories. There are unofficial releases, and I would like to avoid installing them.

My problem is that I can't use this package since PHP 7.1 is required.

I had the exact same problem of infinite loading before upgrading `ide-php` to the last version.

**Comment by felixfbecker** [comment]
The language server is tested against 7.0

**Comment by pelallemant** [comment]
Yes but the atom ide-php requires 7.1 since a few commits. 
https://github.com/atom/ide-php/commit/ac8bdb4cfd838db112707e5931fb2794a7f1a234

**Comment by felixfbecker** [comment]
Cool, unsubscribing from this thread then cause if it's not an issue in the langserver

**Comment by damieng** [comment]
I was under the impression that PHP 7.1 was required from the comment above about it only working on 7.1...

I can change the detection back to 7.0 but if people are finding the language server doesn't run on their system with 7.0 ...

**Comment by damieng** [comment]
@pelallemant Can you open the ide-php package on your machine, the main.js file, and just change the PHP min version to 7.0 and see if it works?

**Comment by pelallemant** [comment]
I changed to 7.0 and I get the same problem than before: "FelixFBecker initializing for specifications" infinite loading.

**Comment by felixfbecker** [comment]
I can't imagine a difference between 7.0 and 7.1 that would cause the language server tests to pass on 7.0 but load forever on 7.0 and not on 7.1. Maybe it's a PHP bug?

**Comment by damieng** [comment]
If you were on Windows I'd maybe put it down to the Windows Defender heuristics being happier with 7.1 but you're on Linux >:-/

**Comment by damieng** [comment]
>PHP (FelixFBecker) stderr ParseError: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/pierre-emmanuel/.atom/packages/ide-php/vendor/symfony/console/Output/Output.php:40

```php
    public function __construct(?int $verbosity = self::VERBOSITY_NORMAL, bool $decorated = false, OutputFormatterInterface $formatter = null)
```

It looks like the Composer Console dependency we have here is for 7.1.3...

**Comment by damieng** [comment]
Should we be using a different composer file or command to create our ZIP of the server and dependencies other than the following? @felixfbecker 

```json
{
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "felixfbecker/language-server": "^5.3.6"
    },
    "scripts": {
        "parse-stubs": "LanguageServer\\ComposerScripts::parseStubs",
        "post-update-cmd": "@parse-stubs",
        "post-install-cmd": "@parse-stubs"
    }
}
```

```bash
rm -rf vendor && rm composer.lock && composer install --prefer-dist --no-dev && composer dump-autoload --optimize
```

**Comment by felixfbecker** [comment]
Is there a reason why you commit `composer.lock` to the repo but then delete it?

`symfony/console` is a transitive dependency so the latest compatible version with the machine running the build will get pulled in. If you run the build on a machine with PHP 7.0 it should install the versions of packages compatible with 7.0. Example: https://github.com/felixfbecker/php-language-server/blob/e10896f90554c2f95b052c09fbc3685e84fb9a60/.travis.yml#L40

Not sure what your release process is here?

**Comment by pelallemant** [comment]
The version of symfony/console "v4.0.4" isn't compatible with php 7.0. 
If i remove the composer.lock and run composr install in another folder, the version i get is v3.4.5.

**Comment by felixfbecker** [comment]
Yes. The requirement is `^2.7 || ^3.0 || ^4.0`. All you need to do is run Composer with PHP 7.0, not 7.1.

**Comment by damieng** [comment]
Okay, I've recreated our download zip (we wanted to avoid our users having to run Composer) from php 7.0 and updated to the new 5.3.7 language server.  Thanks for all your help @pelallemant and @felixfbecker

**Comment by felixfbecker** [comment]
Yeah I do the same for VS Code, I just generate the vsix (which is just a fancy zip) in CI

**Comment by vinkla** [comment]
I've pushed a fix to make Composer think we always want PHP 7.0 dependencies to avoid future hickups: https://github.com/atom/ide-php/commit/53d4d253f58da3b8da4b42f6ab638ac6fcb248ac

**Comment by pelallemant** [comment]
@damieng already solved the issue, the problem was that the composer.lock published was built from a 7.1 env.
I think the fix you made will make ide-php bug if the environments has only PHP 7.1 or 7.2 ..

**Comment by vinkla** [comment]
> @damieng already solved the issue, the problem was that the composer.lock published was built from a 7.1 env.

With [this commit](https://github.com/atom/ide-php/commit/53d4d253f58da3b8da4b42f6ab638ac6fcb248ac) this wont be an issue in the future.

**Comment by pattonwebz** [comment]
I should have dug more deeply for this issue before I opened the ticket to try spot what was causing the problem. I am glad the root cause was figured out and fixed for future versions :)

**Comment by arkenidar** [comment]
I discovered (in the hard way) I had not installed Composer.

**Comment by ShivamS136** [comment]
I am still having the same problem in Window 10 with the latest Atom.

**Comment by jeitnier** [comment]
I have the same issue as @ShivamS136 on Windows 10, php 7.4.1 `FelixFBecker initializing for {PROJECT_NAME}`

**Comment by devslyfox** [comment]
> I have the same issue as @ShivamS136 on Windows 10, php 7.4.1 `FelixFBecker initializing for {PROJECT_NAME}`

Find file
...\.atom\packages\ide-php\composer.json
Change line on:
"platform": {
            "php": "7.1"
        }
Doesn't work with older versions of php
Next:
cd ...\.atom\packages\ide-php
php composer update
