### ISSUE TITLE
Starting FelixFBecker for [projectname]

### ISSUE THREAD

**Issue by philicevic** [atom/ide-php#107]
Every time I try to open a php file in my project, atom is not able to use the IDE-Features as it did before. It just shows me the loading icon in the outline view and at the bottom and says "Starting FelixFBecker for [projectname]".
I reinstalled atom and every package but still the same problem.
I'm working on Windows 10.

**Comment by vinkla** [comment]
What version of PHP are you using? Make sure you're running at least PHP 7.1.

**Comment by philicevic** [comment]
I was using 7.0.21, changed it to 7.1.7 and now its working again! Thanks a lot! :)
Somehow i missed the 7.1-requirement..

**Comment by vinkla** [comment]
In future versions of this package the PHP requirement will alert the user: ac8bdb4cfd838db112707e5931fb2794a7f1a234
