### ISSUE TITLE
Feature Request: parsing loading spinner

### ISSUE THREAD

**Issue by pelallemant** [atom/ide-php#110]
Hi,

When we have a "big" PHP project, the autocompletion isn't available before a long time, the time for FelixFBecker php language-server to parse the whole project (in the worst case).

There are notifications from FelixFBecker like "window/logMessage", whose message contains "Parsing file:///". 
Could it be possible to add another loading spinner with a percentage of files parsed or information to tell us that the plugin is launching parsing requests ?

**Comment by damieng** [comment]
Messages about indexing progress would need to be performed upstream - the Eclipse Java JDT does something similar using the 'status' message. We could then easily wire them in here.  

In the mean time the logMessages are now available in the Console window inside Atom IDE UI so it's a little bit improved.
