### ISSUE TITLE
Autocomplete etc. from custom library.

### ISSUE THREAD

**Issue by Oshawk** [atom/ide-php#114]
Hello,

Apologies if this is a very stupid question, I am very new to PHP development. How would I go about getting complementation for a custom library, I have seen people say to just clone the code to the project folder but this does not seem to work. Not sure if this is a language server thing or what.

Thanks,
Joseph.

**Comment by damieng** [comment]
Not sure why this happens yet but I believe it is the same issue as https://github.com/atom/ide-php/issues/18
