### ISSUE TITLE
Updating failed - EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by appleandpear** [atom/ide-php#115]
Since few versions ago, every time when I'm updating ide-php package, updater returns error:

> Updating to "ide-php@`<version>`" failed.
> EBUSY: resource busy or locked, rmdir `'C:\Users\<user_login>\.atom\packages\ide-php\vendor'`

where: `<version>` is the number of the new version that updater is trying to install (current: 0.7.11).
After that, the package is available in Atom packages list, but it seems to not installed well - the settings button disapeared. Also noticable is that package is not working, but in packages list is displayed as enabled. Then I have to uninstall and install ide-php again, then it comes with new version and working well.
All other packages are updating automatically without any errors.
Is it can be related with opened .php files in the background in Atom?

Current installed version ide-php: 0.7.9
Atom version: 1.24.1
OS: Windows 10 Pro x64
Free disk space: 113GB

**Comment by damieng** [comment]
You need to close any php files that are open before the package can update - we're looking into having Atom send packages notifications they are upgrading but right now the server has no way of knowing it should stop to allow the upgrade to take place.

**Comment by damieng** [comment]
Tracking this issue in https://github.com/atom/ide-php/issues/32
