### ISSUE TITLE
Diagnostic

### ISSUE THREAD

**Issue by cloudbluedigital** [atom/ide-php#116]
Hi,

I have noticed that this package does support diagnostic, however what I do not have is diagnostic next to the code, unless I hover over the error Is there a way to always show it even when i don't hover?

Without Hover:

![1](https://user-images.githubusercontent.com/22678404/37524238-2977acc4-2921-11e8-8f57-583a55d79d0c.jpg)

With Hover:

![2](https://user-images.githubusercontent.com/22678404/37524239-29915624-2921-11e8-90e3-1a5b51160e26.jpg)

**Comment by damieng** [comment]
The errors are shown at the bottom of the screen in the diagnostics pane.  There is no feature to display them all in-line like in the hover mode.  You could ask for this feature in the Atom IDE UI package although I'm not sure how well this would work - if you have lots of errors it could get unusable while you try and fix them.
