### ISSUE TITLE
Remote PHP server

### ISSUE THREAD

**Issue by tealborder** [atom/ide-php#119]
Any chance for remote PHP in a VM? I get the following

> IDE-PHP could not launch your PHP runtime.
> No PHP interpreter found at php.
> 
> If you have PHP 7.0 installed please Set PHP Path correctly. If you do not please Download PHP 7.0 or later and install it.

**Comment by fabiomontefuscolo** [comment]
Indeed, it would be useful to run the Language Server in other to check, kill or restart when it starts to consume a lot of CPU. It is taking 100% of my computer right now and I'm trying to figure out why this happens. If we could spawn server on a docker container or VM and watch logs, it would help to investigate.

I think somewhere here we could read from config https://github.com/atom/ide-php/blob/master/lib/main.js#L121

**Comment by damieng** [comment]
We have no plans to support remote servers.
