### ISSUE TITLE
atom-autocomplete-php failure

### ISSUE THREAD

**Issue by namelessolo** [atom/ide-php#122]
PHP autocomplete not working correctly inside php tags it makes no suggestions.

My settings for Mint 19

Comand to use composer
/usr/local/composer/bin

Comand php
php

**Comment by phh** [comment]
+1 have the same issue.

**Comment by vinkla** [comment]
This seems to be an issue with the `atom-autocomplete-php` package. [Please open an issue in their repository.](https://atom.io/packages/atom-autocomplete-php)
