### ISSUE TITLE
How to use the "Go to definition" feature

### ISSUE THREAD

**Issue by damms005** [atom/ide-php#124]
This is simple enough I guess: one of the items listed under the "Features" of ide-php is "Go to definition
".
However, it is simply unclear from any source how to do this. Keyboard shortcuts? etc...

Please help.

Thanks

**Comment by Jarvizx** [comment]
I have the same issue.

**Comment by StuffieStephie** [comment]
<kbd>alt</kbd> + <kbd>click</kbd>!  You can change this in the parent package (Atom-ide-UI) under Settings >> Hyperclick.

**Comment by vinkla** [comment]
Thanks for helping out @StuffieStephie!
