### ISSUE TITLE
Incorrect project path

### ISSUE THREAD

**Issue by sharifzadesina** [atom/ide-php#126]
Why this happens?
The "personal" is one of my old projects, "bugbounty" is my current working project.
I also renamed current project, restarted atom, but nothing changed.
Bugs like this (but with different path as "personal") mostly happens on my projects.

![2018-08-11_11-52-40](https://user-images.githubusercontent.com/15300551/43989341-47361a6a-9d5d-11e8-9251-e67841c278e0.gif)

**Comment by vinkla** [comment]
Not sure what your issue is here. Please provide a more thorough description with what versions you're using, your error messages and a step-by-step guide on how we can reproduce this issue.

**Comment by sharifzadesina** [comment]
@vinkla I've attached a GIF to the issue, if you saw it, you will get what's the problem.

**Comment by vinkla** [comment]
Please always provide as much information as you can when you open issues on GitHub.

> _When a person reviews an Issue Request there should be enough information that they have a good handle of what is being discussed, they don’t need to know or come up with a solution instantly, but nothing about the issue should be mystery meat - [UpThemes](https://upthemes.com/blog/2014/02/writing-useful-github-issues/)_

I'll go ahead and close this.

**Comment by sharifzadesina** [comment]
@vinkla The GIF were better than any text, but no cares. let the bug stay on the source.
