### ISSUE TITLE
win10 x64 fresh install not working?

### ISSUE THREAD

**Issue by erfg12** [atom/ide-php#133]
- Installed Atom 1.32.2 for Windows x64.
- Added atom-ide-ui
- Added ide-php
- Installed WAMP
- Added PHP bin file and path to ide-php setting

Made a new test.php file on desktop. 

Typed in strstr( and no context comes up. 

Checking the "Outline" view shows "No Outline Available - This is likely an error with the language package."

Am I missing something? How can I see debug files or logs if there's some un-seen issue?

**Comment by vinkla** [comment]
1. Did you see the language server initiating in the status bar?
2. Please provide your PHP path setting.

**Comment by erfg12** [comment]
1. I see PHP down at the bottom right corner.
2. C:\wamp64\bin\php\php7.0.32\php.exe

**Comment by damieng** [comment]
Also try opening the dev tools indow and entering
atom.config.set('core.debugLSP', true) then restarting atom. You should see
light messages.

**Comment by vinkla** [comment]
Looks like you’re using the `atom-autocomplete-php` package. It provides a similar behavior. Try disabling that package and restart Atom.

**Comment by vinkla** [comment]
This seems to be an issue in the `atom-autocomplete-php` package. Please see this issue: https://github.com/Peekmo/atom-autocomplete-php/issues/393
