### ISSUE TITLE
Support docker based php runtime

### ISSUE THREAD

**Issue by marfillaster** [atom/ide-php#14]
In settings > PHP Path

**Comment by damieng** [comment]
I'm not sure what this would involve - do you have more information?

**Comment by marfillaster** [comment]
Assuming docker client is available in path, a simple

**Comment by alexandernst** [comment]
I believe what @marfillaster is trying to say is that a normal workflow nowadays involves running a project from inside a docker container, instead of running it on bare metal. Moreover, usually the version that is used in the container of a project doesn't match the version installed on the host system (typical scenario being MacOS with PHP 5.x versus a docker container running PHP 7.x).

It would be nice if ide-php (or actually any ide-* package in Atom) would, somehow (I'm completely aware this is technically very difficult to achieve), manage to use the PHP binaries from inside the docker, instead of using the local system ones.

**Comment by damieng** [comment]
So use the binaries from inside a docker container against the files held on your local file system?  I think the setup for that would be non-trivial and isn't something we could easily hide behind this package.

If somebody else wants to pick this up and it doesn't negatively impact non-docker users I'd be up for adding it.

**Comment by alexandernst** [comment]
@damieng Yes, exactly. The idea would be to use whatever language interpreter (PHP, Python, Ruby, etc...) lives inside the container to power the ide-* packages. As I said, doing this is not impossible, but technically speaking would be very difficult. Maybe some sort of server running inside the container and communicating via SSH?

**Comment by damieng** [comment]
I think given the complexity it's out of scope for this package. That's not to stop somebody else creating a fork or alternative version but given it's something I wouldn't be able to support even taking a PR would be problematic.

**Comment by alexandernst** [comment]
Fair enough. But this is still a valid concern to have, and since docker is growing and growing among developers, imho, this should be handled at some point. Is there any specific place where a new feature request could be created to track this? Maybe a common ide-* repository?

**Comment by damieng** [comment]
We're trying to avoid having open issues for stuff we have no intention of working on - it gives people the impression we'll get to it when we won't.  Additionally it means the issues we do want to work on get cluttered in the noise.

If somebody wants to work on a docker version they will - I don't think us maintaining a centralized list of requests would cause somebody to do it. They'll either want to scratch their own itch or they won't - that's the reality of open source development.

**Comment by mateusz-kolecki** [comment]
Running language server in docker:

1) Create bash script, in my case it is: `/home/mateusz/bin/php-docker-for-atom-ide`

```bash
#!/usr/bin/env bash
docker run -i -v $(pwd):/mnt php:7.2 sh -c "cd /mnt && php $@"
```
2) `chmod +x /home/mateusz/bin/php-docker-for-atom-ide`

2) Set PHP Path as absolute path to the script
![image](https://user-images.githubusercontent.com/4613412/43689305-cb35074a-98f8-11e8-8bd6-bcea943f5eaa.png)
