### ISSUE TITLE
Atom-ui-ide has stopped updating whether to change the interface or not

### ISSUE THREAD

**Issue by linjialiang** [atom/ide-php#140]
Atom-ui-ide has stopped updating whether to change the interface or not

**Comment by Arcanemagus** [comment]
`ide-php` interacts through services, as such it doesn't _directly_ depend on `atom-ide-ui`. You can follow [Atom IDE Community](https://atom-ide-community.github.io/) for efforts on creating maintained replacements for the functionality.

**Comment by linjialiang** [comment]
>Can I install these plug-ins to support `ide-php`

![image](https://user-images.githubusercontent.com/8848263/54166777-b5adcb00-44a1-11e9-9f3a-19e3becccc3f.png)
