### ISSUE TITLE
Should you write a separate version for atom-ide-community

### ISSUE THREAD

**Issue by linjialiang** [atom/ide-php#147]
Should you write a separate version for atom-ide-community

> For atom-ide-community, there is a lot of unnecessary content in the plug-in

**Comment by Arcanemagus** [comment]
The goal of this package is to implement the features of [FelixFBeckers PHP Language Server](https://github.com/felixfbecker/php-language-server) in the Atom ecosystem, if there are parts of that supported by this package but not yet supported by the set of packages from `atom-ide-community` you should file an issue there about adding the missing support 😉.

Thanks for taking the time to file an issue!
