### ISSUE TITLE
Incorrect Brace Highlighting / Incorrect PHP Parsing

### ISSUE THREAD

**Issue by mikebronner** [atom/ide-php#17]
It appears that the PHP parse might not be working correctly. The following screenshots show incorrect syntax highlighting on braces, as well as incorrect PHP validation:

<img width="998" alt="screen shot 2017-09-13 at 9 53 33 am" src="https://user-images.githubusercontent.com/1791050/30390026-9bf4648e-9869-11e7-87b3-866cd8ef8d26.png">
<img width="990" alt="screen shot 2017-09-13 at 9 53 47 am" src="https://user-images.githubusercontent.com/1791050/30390029-9f90bf7a-9869-11e7-836e-067a6bceace0.png">

(Posting this two things together, as they might be related?)

**Comment by damieng** [comment]
Was this immediately on open?  If so I suspect any issue would be in the language server itself.

ide-php really is just a bridge from the php language server to atom and doesn't get involved in syntax validation etc.   (It does however get involved in syncing documents so if this only happens when you've changed this file it could be an ide-php problem)

**Comment by mikebronner** [comment]
Ah, yes, this is already formatted that way immediately when opening any PHP file. Is the language server part of atom-ide-ui? Where would you recommend I report this issue? (Sorry, just installed Atom IDE yesterday, so fresh to this environment.) :)

**Comment by damieng** [comment]
The underlying language server is https://github.com/felixfbecker/php-language-server (it's in the README). I'd suggest checking there to see if there are any known issues etc.

**Comment by mikebronner** [comment]
Thanks, would the PHP parsing errors be part of the same issue, or is that basically that the detected errors didn't go away after they were fixed (issue #19)?

And thanks for all the hard work you guys are putting into this!!

**Comment by 50Wliu** [comment]
Syntax highlighting has been fixed but not yet released in an Atom version.

**Comment by mikebronner** [comment]
Thanks for the info, @50Wliu !! Looking forward to that. :)
