### ISSUE TITLE
Language server failed if there are files open

### ISSUE THREAD

**Issue by markwu** [atom/ide-php#22]
After install ide-php, everything works fine, the outline view show functions without any problems.

But, after restart ATOM, the spinning wheel keeps spinning inside outline view. After several minuts, it showed "Not available outline".

I have to close all files and restart the ATOM again, then open the same file, then  I can show outline again.

It seems language server  does not start correctly/successfully when there are files open on ATOM startup stage.

I use ATOM 1.21.0-beta0 under macOS 10.12.6 with ide-php 0.6.2.

**Comment by djouuuuh** [comment]
Hi. 

I'm having the same issue. It's working fine with JavaScript files but not with PHP. 

I was wondering if it's not because I made a mistake in the PHP Path settings. 

That's what I've got: `/Applications/MAMP/bin/php/php7.1.6/bin/php`. 

Does it seem correct?

Thanks

**Comment by SpencerSharkey** [comment]
My outline view endlessly spins too- files open during the start or not. No errors in dev tools, or on status bar. PHP path is set to a normal PHP 7 install.

**Comment by mikebronner** [comment]
For me the outline view seems temperamental. On some php files it shows, on some it doesn't. Haven't been able to nail down why, but in my case I don't need to restart Atom, just go to a different file, and it may or may not show up for that file. Going back to a file that previously didn't work doesn't seem to work after restarting atom (without any files open) either.

**Comment by thepenguin1** [comment]
I can confirm similar behaviour.

**Comment by rsese** [comment]
Thanks for the reports everyone - does anyone have a public project that shows this behavior?  If so, can you share the URL of the repository and exact steps to reproduce?

**Comment by thepenguin1** [comment]
You don’t need a public repository / specific code. It happens all the time on any project :)

**Comment by rsese** [comment]
> You don’t need a public repository / specific code. It happens all the time on any project :)

😄  - it sounds intermittent for other folks and I'm unable to reproduce.

On macOS 10.12.16, I tried with ide-php 0.6.9:

```
$ atom -v
Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ php -v
PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

And these 2 simple PHP files:

```php
<?php
function foo() {
  echo "<p>Hello World!</p>";
}
?>

<html>
 <head>
  <title>Hello World</title>
 </head>
 <body>
 <? foo(); ?>
 </body>
</html>
```

```php
<?php
function bar() {
  echo "<p>Hello World!</p>";
}
?>

<html>
 <head>
  <title>Hello World</title>
 </head>
 <body>
 <? bar(); ?>
 </body>
</html>
```

And the outline view works ok with both files.  Does this not work for you either @thepenguin1?

@markwu - since you opened the issue, are you still seeing the behavior you initially described now?

**Comment by rsese** [comment]
We'll go ahead and close for now since there's no more replies to our question in https://github.com/atom/ide-php/issues/22#issuecomment-340140658 but if you're still having trouble, please open a new issue with as much detail as possible to help us reproduce.
