### ISSUE TITLE
Unexpected end of file

### ISSUE THREAD

**Issue by jbrooksuk** [atom/ide-php#24]
I'm getting a lot of the following:

```
Uncaught (in promise) Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:355:17)
```

**Comment by damieng** [comment]
It sounds like somehow the .tar.gz file isn't downloading for you.

Can you check in the ide-php folder on your machine - inside there you'll see a vendor folder and a download.tar.gz - what size is it?

**Comment by damieng** [comment]
No response.

**Comment by jbrooksuk** [comment]
Sorry! Seems to be fixed now.
