### ISSUE TITLE
How to add additional linters?

### ISSUE THREAD

**Issue by mikebronner** [atom/ide-php#25]
I was wondering if there was a process to add additional linters? Specifically I use the following linters in addition to the PHP linter that is included in ide-php:
- phpmd (PHP Mess Detector)
- phpcs (PHP CodeSniffer)

I also like to include the following in my Atom setup:
- html linter
- json linter
- js linter
- markdown linter

So far these have been available through the "linter" package by steelbrain, and I have been able to install it, but it seems to duplicate the linter indicators in the status bar.

What are your thoughts on integrating the ide-php linter with the linter package by steelbrain and including that as a dependency? Or do new packages need to be developed to integrate into ide-php linter?

**Comment by damieng** [comment]
You should be able to run existing Atom linter packages without the core Linter package that provides the UI - the atom-ide-ui diagnostics package uses the linter v2 api just like linter does and should be capable of displaying the results from those linters.

As for bundling additional linters with ide-php - Given there are many to chose from whichever we choose would not suit everybody's need and we'd end up bundling all of them which would make ide-php large and unwieldy. I think we'd rather keep linters separate at this time unless they are part of the underlying language server we're using for each package. They're often just concerned with syntax and semantics much more than formatting and style which leaves a space for linters to fill.

**Comment by mikebronner** [comment]
@damieng Thanks for the fast answer. I will give that a try and report back. (Uninstalling the base linter package now.)

**Comment by damieng** [comment]
Still trying to figure out how to put documentation together. There are many parts and options. Will bear this in mind.
