### ISSUE TITLE
Incorrect errors being reported.

### ISSUE THREAD

**Issue by AustP** [atom/ide-php#26]
Given the following code:

```
<?php

function getEchoFunction()
{
    return function ($message) {
        echo($message);
    };
}

getEchoFunction()('hey');
```

An error is reported. It looks like it doesn't like calling functions inline like that.

> Error: ';' expected. Line 10:18

Changing the code to:

```
$echo = getEchoFunction();
$echo('hey');
```
 
works as expected.

**Comment by roblourens** [comment]
This could be a gap in the parser, https://github.com/Microsoft/tolerant-php-parser/. An issue there, (or a PR!) would be much appreciated.
