### ISSUE TITLE
bracket coloring issue: CSS Specificity error / Class Ordering Issue

### ISSUE THREAD

**Issue by corbanCloud** [atom/ide-php#27]
I noticed that inside of a class there is errors with the coloring of brackets.   It appears to be an issue with CSS class ordering. The bracket is getting the its color style from `.syntax--meta.syntax--class` which is overriding the correct color from `atom-text-editor`

Removing the class `.syntax--class` or placing at the beginning of the class list resolves the issue.
I am not sure if this will cause other issues, but appears to restore expected behavior.

This is not present in my stable Atom with the traditional linter package, only atom beta + ide-php
I have attached 2 images showing the issue.

Issue Only:
![screen shot 2017-09-14 at 11 19 18 am](https://user-images.githubusercontent.com/3440531/30447337-a1569bea-9940-11e7-9b04-733a611866eb.png)

Issue With Inspector Showing Applicable Details:
![screen shot 2017-09-14 at 11 24 30 am](https://user-images.githubusercontent.com/3440531/30447336-a155aac8-9940-11e7-8ea1-a2770ec1649c.png)

Image with `.syntax--class` moved to beginning of class list, which resolves CSS selector issue
![screen shot 2017-09-14 at 11 35 28 am](https://user-images.githubusercontent.com/3440531/30447427-f9a8b472-9940-11e7-95c7-720e15d30eb9.png)

**Comment by damieng** [comment]
Hi! The syntax colorization is actually handled in the https://github.com/atom/language-php package.  (I so wish we had the ability to move issues!)

**Comment by Ben3eeE** [comment]
This issue has already been fixed and will be included in the next hotfix release. /cc: https://github.com/atom/one-dark-syntax/issues/100#issuecomment-328988364

**Comment by corbanCloud** [comment]
Thanks sorry to drop this in the wrong repo!
