### ISSUE TITLE
Question: Is atom/language-php required for this package?

### ISSUE THREAD

**Issue by ccjjmartin** [atom/ide-php#28]
Thanks for making atom better and integrating IDE features!  I searched through the issue queue and readme and couldn't find a reference to if the language-php package is compatible/required with this package?

I don't see it listed as a dependency but I am also not seeing formatting of my php code without it.

**Comment by damieng** [comment]
language-php is required for syntax highlighting but it's bundled with Atom anyway hence wasn't listed as a dependency.
