### ISSUE TITLE
Remove status bar element

### ISSUE THREAD

**Issue by UziTech** [atom/ide-php#29]
The status bar element seems to provide no useful information and takes up real estate that could be used by other useful information.

Could we remove the status bar element or at least add a class so we could set `display: none` in our style sheet if we don't want it.

**Comment by UziTech** [comment]
or at least remove it after downloading the server is complete

**Comment by damieng** [comment]
I'm looking at using the atom-ide busy signal for this which would be much more compact and disappear when not busy.  

Just need busy signal to be able to display the busy text without requiring the user to hover as first-time install is when they're least likely to know to do that.

**Comment by mikebronner** [comment]
I was just about to suggest busy signal ;) looking forward to that1 ;)

**Comment by UziTech** [comment]
@damieng is there an issue or pull request for atom-ide-busy-signal to display the text without hovering?

**Comment by damieng** [comment]
No yet!

**Comment by UziTech** [comment]
I feel like this doesn't need to be displayed without the user hovering. The user would see the busy signal and it is fairly intuitive to hover over an icon for more information. Also the information that would be displayed is not very useful to the user. The percentage that the server is downloaded won't really help the user at all. Just knowing that something is happening in the background should be good enough. And if the user wants to know more they can hover over the loading icon.

**Comment by damieng** [comment]
@UziTech I disagree. The first time people install they need to know it is downloading and installing and that can take some time. They won't know to hover over a tiny icon and we'll just end up with frustrated users and a rash of issues.

The percentage downloaded does help - it gives you an indication of how long it will take to start ide-php.

As soon as ide-busy-signal can auto-pop the text we'll switch.

**Comment by UziTech** [comment]
can we at least get a class added in the mean time so we can hide it if we don't want it?

**Comment by UziTech** [comment]
looks like the busy-signal can reveal the text now https://github.com/facebook-atom/atom-ide-ui/pull/55

is someone working on this or should I submit a pull request?
