### ISSUE TITLE
Documentation improvement for installation and usage

### ISSUE THREAD

**Issue by harikt** [atom/ide-php#3]
Hi, 

I was trying the package.

Cloned the package to `/home/user/.atom/packages` folder. 

Installed the composer dependencies and also ran `apm i` .

Package is installed. Have set the `/usr/bin/php` path. php version is `PHP 7.1.8-2` .

Is there anything else to do for this to work as expected ( clicking class names or methods opening the file etx ) ? Or is still in development ?

I have tried to debug a bit using `console.log` , but it looks the `startServerProcess ()` is not called. 

`getGrammarScopes ()` is called when I put `console.log("Hello World")` .

**Comment by damieng** [comment]
You can switch on detailed debugging by entering this in the dev tools window;

`atom.config.set('core.debugLSP', true)`

Then restart your editor. It should show more detail on the dev tools console window. You will need to open a PHP file for it to start up the server.

**Comment by harikt** [comment]
cool. Thanks for the information.

The server and rpc notifications are send. But not sure why the files are not open etc. May be some other plugins are causing the issue. Have installed some go devel tools also. Will disable all and try again.

**Comment by damieng** [comment]
can you post the contents of your devtools window after opening a .php file?

**Comment by harikt** [comment]
See screenshot :  ![screenshot from 2017-08-16 08-20-55](https://user-images.githubusercontent.com/120454/29345365-ea39ba00-825b-11e7-8f23-41b82d61c61d.png)

**Comment by damieng** [comment]
The ide-php package looks like it's working okay.

Have you installed the `atom-ide-ui` package?  That gives the diagnostics, outline view, find references etc.

**Comment by harikt** [comment]
Multiple reasons : 

* First :
1 . Was using atom 1.16
2. As suggesed tried installing `atom-ide-ui` . ( Was incompatible so upgraded to 1.19 )

* Second : 
1. Installed 1.19
2. The classes or interfaces were not opneded as expected.
3. Installed `atom-ide-ui` 
4. It started working for some files, for some it is still not working.

So not sure what the exact cause after installing atom 1.19 .

Is there some where I can learn how to debug / how things work in this ? I may be able to start looking at some where ?

**Comment by damieng** [comment]
It does require Atom 1.19.  

What do you mean "start working for some files, for some it still not working".  Do you mean diagnostics pane, autocomplete, outline view?...

**Comment by harikt** [comment]
Eg : I can move mouse over `IRepository` or `ctrl` + click on `IRepository` to open the class.

![screenshot from 2017-08-16 10-17-09](https://user-images.githubusercontent.com/120454/29347707-2ebf7434-826c-11e7-9b83-aca8b46f705b.png)

But inside the `IRepository` class the other interfaces are not openable or anything show when you move mouse over. See below 

![screenshot from 2017-08-16 10-16-19](https://user-images.githubusercontent.com/120454/29347740-7293fe00-826c-11e7-8be9-57dc6218a46f.png)

**Comment by damieng** [comment]
Can you clear the console dev tools window, hover over it and then paste in hopefully the two messages you see - one that says "sending hover" the other "receiving hover"

**Comment by harikt** [comment]
for `IRepository` class when you hover on anything, nothing is shown or send. For other classes the requests are send. So the console is empty or nothing to show here.

**Comment by harikt** [comment]
The repo I am playing with is https://github.com/dms-org/core .

**Comment by harikt** [comment]
UPDATE : 

I actually have a laravel installation with dms-core inside it in vendor folder.  http://dms-docs.readthedocs.io/en/latest/docs/getting-started.html

When I opened atom from `vendor/dms-org/core` then the `IRepository` is also working fine. I am not sure what exactly is the reason for the signals are not send when using it on project.

**Comment by damieng** [comment]
There often is lag in language servers as they parse and cache the results of analyzing the source files.

Alas, I am not too well versed on the actual capabilities and performance of the underlying PHP language server this package accesses.

**Comment by harikt** [comment]
ok. Closing for the issue is resolved. I will try to send a PR with readme updates if needed.

**Comment by harikt** [comment]
Actually do you know where the cache is being written ? When I renamed a project folder blank files are opened. 

The project where I am trying is a new one. It is making use of cache than using the new project though. ie another issue I see.
