### ISSUE TITLE
No features working (with Laravel)

### ISSUE THREAD

**Issue by Mythos** [atom/ide-php#30]
Hey there,

I've installed Atom 1.21 Beta and ```atom-ide-ui``` and ```ide-php```. (atom-ide-ui: 0.3.3 and ide-php: 0.6.2)

Installed PHP Version:

![screenshot_2017-09-15 19_55_07](https://user-images.githubusercontent.com/416568/30496491-d4a38778-9a4f-11e7-8457-2189757a15d5.png)

(I'm using XAMPP as it is kinda convenient requiring minimal setup, php.exe is in the PATH as you can see)

When I create a new [Laravel](https://github.com/laravel/laravel) project, the features of Atom IDE are not working unfortunately.

For example, the not working Hyperclick feature:

![screenshot_2017-09-15 19_48_15](https://user-images.githubusercontent.com/416568/30496280-308ac5de-9a4f-11e7-967d-bd43bcfa1690.png)

Opening the autocomplete does nothing. (CTRL + Space)

![screenshot_2017-09-15 19_52_56](https://user-images.githubusercontent.com/416568/30496384-80eed1aa-9a4f-11e7-9290-01328586b5e7.png)

Also obvious syntax errors are not highlighted or anything like that.

![screenshot_2017-09-15 19_51_26](https://user-images.githubusercontent.com/416568/30496322-4cf6e86a-9a4f-11e7-85cb-9d0a22019fa8.png)

The output of the console window doesn't show any error:

![screenshot_2017-09-15 19_54_04](https://user-images.githubusercontent.com/416568/30496435-a8a04238-9a4f-11e7-83d8-956d7fc7f7b3.png)

Does anyone know what I could have done wrong?

Best Regards,
Stefan

**Comment by mikebronner** [comment]
I will let others hypothesize what might be wrong (I would guess installation issue?), but I don't think it is related to Laravel, as most things work in my Laravel setup (using Homestead, but I don't think that is the issue either).

What has not been working for me is autocompletion (it seems to work only for items of the current file, there seem to be issues with autocompletion working across composer dependencies or composer auto-loading.

**Comment by Mythos** [comment]
I've already uninstalled Atom already and deleted the ```.atom``` folder in my user directory.
Unfortunately it didn't change anything, still none of those features are working.

**Comment by damieng** [comment]
Thanks for the log details stefan.

It looks like it is launching the language server and connecting but then
it is failing to communicate (it sends an initialize message but doesn't
get a response).

I'm going to put out an updated version today that adds some additional
logging and lets you try an alternative communication mechanism.

**Comment by damieng** [comment]
I've published a new version that should output some additional logging details. It's very strange - it's launching on your system then just not communicating with it... Hopefully the logs will reveal something.

**Comment by damieng** [comment]
@Mythos I just realized it says you have php 6?  The language server requires 7.1

**Comment by Mythos** [comment]
Good morning @damieng,

finally we have more information, thanks for the quick update. :-)
Somehow memory allocation doesn't work with "-1":

![screenshot_2017-09-16 08_21_51](https://user-images.githubusercontent.com/416568/30509766-42f47670-9ab8-11e7-839d-0d28da23fd87.png)

As you can see, my system memory is at around 36% and in the settings I allow the server to use unlimited RAM, but it still crashes because it ran out of memory.

**Comment by Mythos** [comment]
Also with max. 8GB it crashes. But it tries to start it with a limit of 8GB though.

![screenshot_2017-09-16 08_26_09](https://user-images.githubusercontent.com/416568/30509788-b94d8870-9ab8-11e7-8414-3c55ec3852a8.png)

**Comment by 3Descape** [comment]
![unbenannt](https://user-images.githubusercontent.com/5028761/30515365-5771e128-9b26-11e7-9c4c-498641dc73fe.png)
I use laravel too and I it seems like the memory problem occures here as well.

**Comment by damieng** [comment]
It doesn't seem to be honoring the memory limit flag...  I'll try and investigate some more tonight and try the 32-bit PHP runtime.

**Comment by damieng** [comment]
Found the problem with the memory limit.  It will now default to 2GB for everyone so that should solve the issue on 32-bit systems.

Additionally if the PHP server should exit abnormally it will display the error message in an atom notification which should help with further debugging of similar issues.

**Comment by 3Descape** [comment]
I can confirm that it is working now. Thank you very much for the fix.  Autocomplete seems to not understand most of the methods laravel provides e.g for a model and somethimes even methods within the same file, but I think it got already mentioned that it has difficulties understanding composer dependencies, right? 
Great job so far! I'm sure you will make Atom even better than it is and I can't thank you enougth for this package already!

**Comment by damieng** [comment]
I believe the memory and hanging issues are now resolved. Please open a new issue if you still experience problems in 0.6.7.

**Comment by jens1o** [comment]
>Great job so far! 

Please don't forget that a lot of this handles the `php-language-server` by @felixfbecker :) He should be praised, too :)

**Comment by damieng** [comment]
He should get practically all the praise - this is just a thin installer
using the atom-languageclient adapter.
