### ISSUE TITLE
Package not installing

### ISSUE THREAD

**Issue by mbaljeetsingh** [atom/ide-php#33]
A few things to know before you create an issue

* This package requires [Atom 1.21 beta](https://atom.io/beta)
* We launch a "language server" process on your machine that understands the language you are editing
* What that server can do - syntax compatibility, whether it supports formatting or outlines etc - is outside of our control
* You can see what the language server supports by checking out our README and following the link after "powered by"
* "disconnected", "JSONRPC" or "Content-Header" errors indicate that server process died. We're working on better recovery right now

1. Installed the latest atom
2. Installed ide-typescript 
3. Tried installing ide-php (compatibility error)

**Comment by damieng** [comment]
Are you using Atom 1.20 stable or Atom 1.21 beta?

Atom 1.21 beta is required as explained in the README and the issue notes
