### ISSUE TITLE
PHP language server stopped unexpectedly.

### ISSUE THREAD

**Issue by mikebronner** [atom/ide-php#39]
I know there are a few other issues discussing language server problems, but I thought it might be beneficial to open a new issue dedicated to the new error reporting in 0.6.6. I just received this error:

<img width="623" alt="screen shot 2017-09-18 at 9 32 47 am" src="https://user-images.githubusercontent.com/1791050/30552890-5fa312de-9c54-11e7-8d07-822ee5c84475.png">

```
PHP Fatal error: Allowed memory size of 8589934592 bytes exhausted (tried to allocate 262144 bytes) in /Users/mike/.atom/packages/ide-php/vendor/felixfbecker/language-server/src/FqnUtilities.php on line 25
```

My ide-php settings look like this:
<img width="1004" alt="screen shot 2017-09-18 at 9 34 03 am" src="https://user-images.githubusercontent.com/1791050/30552953-89d547ac-9c54-11e7-8c3f-a9dbe7865112.png">

(Nevermind the php path, it is actually php 7.1.)

#### Atom
1.21.0-beta0

#### macOS
10.13.0 (build 17A362a)

#### php
PHP 7.1.9 (cli) (built: Sep  7 2017 21:03:02) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans

### Installed Packages
```
Built-in Atom Packages (92)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.8
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.8
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.3
├── autocomplete-css@0.17.3
├── autocomplete-html@0.8.1
├── autocomplete-plus@2.35.9
├── autocomplete-snippets@1.11.1
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.41.1
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.5
├── exception-reporting@0.41.4
├── find-and-replace@0.212.2
├── fuzzy-finder@1.5.8
├── github@0.5.1
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.62.3
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.13
├── metrics@1.2.6
├── notifications@0.69.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.251.8
├── snippets@1.1.4
├── spell-check@0.72.2
├── status-bar@1.8.13
├── styleguide@0.49.6
├── symbols-view@0.118.0
├── tabs@0.107.2
├── timecop@0.36.0
├── tree-view@0.217.9
├── update-package-dependencies@0.12.0
├── welcome@0.36.5
├── whitespace@0.37.2
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.4
├── language-coffee-script@0.49.0
├── language-csharp@0.14.2
├── language-css@0.42.5
├── language-gfm@0.90.1
├── language-git@0.19.1
├── language-go@0.44.2
├── language-html@0.47.7
├── language-hyperlink@0.16.2
├── language-java@0.27.4
├── language-javascript@0.127.3
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.41.0
├── language-property-list@0.9.1
├── language-python@0.45.4
├── language-ruby@0.71.3
├── language-ruby-on-rails@0.25.2
├── language-sass@0.61.1
├── language-shellscript@0.25.3
├── language-source@0.9.0
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.2
├── language-toml@0.18.1
├── language-typescript@0.1.0
├── language-xml@0.35.2
└── language-yaml@0.30.2

Community Packages (18) /Users/mike/.atom/packages
├── atom-ide-ui@0.3.3
├── close-on-left@0.9.2
├── file-icons@2.1.11
├── ide-json@0.1.0
├── ide-php@0.6.6
├── ide-typescript@0.6.1
├── ide-vue@0.1.3
├── intentions@1.1.5
├── language-blade@0.35.0
├── linter-csslint@2.0.0
├── linter-json-lint@0.1.2
├── linter-markdown@5.2.0
├── linter-phpmd@1.5.3
├── linter-scss-lint@3.1.1
├── linter-tidy@2.3.1
├── platformio-ide-terminal@2.6.0
├── sync-settings@0.8.3
└── zentabs@0.8.8
```

After this error occured, I reset the ide-php settings to connection type `auto` and memory allocation `-1`, then quit and restarted Atom.

**Comment by mikebronner** [comment]
And starting to type in a php file after changing the settings as mentioned above, resulted in the following error:

```
PHP Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes) in /Users/mike/.atom/packages/ide-php/vendor/felixfbecker/language-server/src/FqnUtilities.php on line 25
```

This seems to indicated that the memory allocation of `-1` is actually only allocating 2G, as suggested in some other issue threads. I am now changing the setting to 16G. If that also causes memory allocation issues, it seems that the language server or this package might have a major memory leak.

**Comment by mikebronner** [comment]
Looks like that is the case:

```
PHP Fatal error: Allowed memory size of 17179869184 bytes exhausted (tried to allocate 262144 bytes) in /Users/mike/.atom/packages/ide-php/vendor/felixfbecker/language-server/src/FqnUtilities.php on line 25
```

I think no matter what memory limit we designate, it seems to always run out of memory.

**Comment by damieng** [comment]
Yes, I defaulted it to 2GB for now but that should be more than enough. It definitely seems to have a memory leak of some description.

We'll need to report the error upstream.

**Comment by jens1o** [comment]
This already has been fixed in the develop branch: https://github.com/felixfbecker/php-language-server/commit/a4739430f82063ac0a1800a12bbe94d01fb1128f

Maybe @felixfbecker can make a new release including the bugfix for this memory leak.

**Comment by damieng** [comment]
Will include the new version of language server in todays update.

**Comment by felixfbecker** [comment]
This should already released?

![image](https://user-images.githubusercontent.com/10532611/30564128-e31141c6-9c78-11e7-8832-ecd9b2b2080f.png)

**Comment by damieng** [comment]
Yeah, sorry, somehow I missed the 4.6.1 update. Have just checked in the code to download a binary package.

Will go out in an update later today.
