### ISSUE TITLE
How to use ide-php

### ISSUE THREAD

**Issue by zestllankesh** [atom/ide-php#4]
Hi,

I am new to atom. 
I want to use atom as php ide.
I've cloned this in ~/atom folder.
Then I ran following commands inside ~/atom folder
1. apm i
2. composer install

I have php7.1 on my mac.
And atom v1.19.5 x64

Is there any document that can help me to use ide-php?
I have no clue on how to use it

**Comment by 50Wliu** [comment]
Sorry for the trouble @zestllankesh, and thanks for reading the instructions before posting an issue :100:.  Unfortunately, as this repository is still experimental, some of the instructions haven't been finished.

Can you try installing [atom-ide-ui](https://atom.io/packages/atom-ide-ui) as well?

**Comment by zestllankesh** [comment]
Okay. Thanks. Will try that
