### ISSUE TITLE
Versioning inconsistency causes composer resolution issues.

### ISSUE THREAD

**Issue by mikebronner** [atom/ide-php#40]
I noticed that ide-php 0.6.6 was tagged two days ago, while versions 0.6.4 through 0.6.5 were tagged today. Could a 0.6.7 version be released with all the latest to make sure the incorrect version is not pulled (if composer resolves something like ^0.6 or 0.6.*)? Atom is displaying the 0.6.6 as the latest version, which will cause the latest releases to be ignored.

If you're already working on this, please close. Just wanted to make sure it wasn't overlooked. :) Thanks!

**Comment by Arcanemagus** [comment]
Composer doesn't use Atom's package manager, so that should have no bearing on this. Atom correctly uses the latest version as you already saw 😉.

**Comment by mikebronner** [comment]
@Arcanemagus  Atom uses composer to install the packages, that is what I was referencing. 0.6.6 is **not** the latest version; 0.6.5 is (see the version history in this package).

**Comment by damieng** [comment]
0.6.6 is the latest version, it is what Atom and apm will install.

The releases tab on this project is just for the change log. The dates/order of the releases tab on GH has no bearing on it.

**Comment by mikebronner** [comment]
@Arcanemagus my apologies -- I was going off the github versions, and not the atom versions.
