### ISSUE TITLE
Error "atom ide-php requires php 7 or later but found"

### ISSUE THREAD

**Issue by sharpeenko** [atom/ide-php#43]
I have that error. But I have php-fpm7.1 and I set path to php in setting. Maybe, I have it, becouse installed php-fpm? 
But it worked yesterday.

**Comment by ergonomicus** [comment]
So, what was the problem?

**Comment by damieng** [comment]
I suspect this was caused by the change in the config from previously using the path to where it could find a 'php' file to specifying the full path.
