### ISSUE TITLE
Hyperclick Requests Incorrect URI

### ISSUE THREAD

**Issue by corbinhesse** [atom/ide-php#44]
A hyperclick from a datatip opens an incorrect URI that is no longer on my system.

I have had multiple Laravel 5.5 projects open in Atom Beta since this package came out, and the URI that hyperclick redirects to no longer exists in my system. I'm assuming this must have been the first project I opened with `ide-php`. Therefore, it opens an empty file.

The `ide-php` has been uninstalled and reinstalled using `apm-beta` command and the issue still persists.

**Path of current project**
`~/Documents/y7-cms/database/seeds/DatabaseSeeder.php`

**Path of hyperclick incorrect redirection**
`~/Documents/visualizer/vendor/laravel/framework/src/Illuminate/Database/Seeder.php`

**Path that hyperclick should return**
`~/Documents/y7-cms/vendor/laravel/framework/src/Illuminate/Database/Seeder.php`

![screen shot 2017-09-22 at 10 07 01 am](https://user-images.githubusercontent.com/4355830/30751245-5dda5494-9f7e-11e7-9a98-596858f021d3.jpg)

Thank you!

**Comment by jakobjohansson** [comment]
got the same issue

**Comment by damieng** [comment]
I think this must be a problem with the language server, they might have an issue for it at https://github.com/felixfbecker/php-language-server
