### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by akapa100** [atom/ide-php#48]
PHP autocomplete not working correctly inside php tags it makes no suggestions.
Outside PHP tags working completely fine

My package list:
[36mBuilt-in Atom Packages[39m (92)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.8
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.8 (disabled)
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.3
├── autocomplete-css@0.17.3
├── autocomplete-html@0.8.1
├── autocomplete-plus@2.35.9
├── autocomplete-snippets@1.11.1
├── autoflow@0.29.0 (disabled)
├── autosave@0.24.3
├── background-tips@0.27.1 (disabled)
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.41.1
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.5
├── exception-reporting@0.41.4
├── find-and-replace@0.212.2
├── fuzzy-finder@1.5.8
├── github@0.6.2
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.62.3
├── incompatible-packages@0.27.3 (disabled)
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3 (disabled)
├── link@0.31.3
├── markdown-preview@0.159.13
├── metrics@1.2.6 (disabled)
├── notifications@0.69.2 (disabled)
├── open-on-github@1.2.1
├── package-generator@1.1.1 (disabled)
├── settings-view@0.251.8
├── snippets@1.1.4
├── spell-check@0.72.2 (disabled)
├── status-bar@1.8.13
├── styleguide@0.49.7 (disabled)
├── symbols-view@0.118.0 (disabled)
├── tabs@0.107.2
├── timecop@0.36.0
├── tree-view@0.217.9
├── update-package-dependencies@0.12.0
├── welcome@0.36.5 (disabled)
├── whitespace@0.37.3 (disabled)
├── wrap-guide@0.40.2 (disabled)
├── language-c@0.58.1 (disabled)
├── language-clojure@0.22.4 (disabled)
├── language-coffee-script@0.49.0
├── language-csharp@0.14.2 (disabled)
├── language-css@0.42.5
├── language-gfm@0.90.1
├── language-git@0.19.1
├── language-go@0.44.2 (disabled)
├── language-html@0.47.7
├── language-hyperlink@0.16.2
├── language-java@0.27.4 (disabled)
├── language-javascript@0.127.3
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3 (disabled)
├── language-mustache@0.14.1
├── language-objective-c@0.15.1 (disabled)
├── language-perl@0.37.0 (disabled)
├── language-php@0.42.0
├── language-property-list@0.9.1
├── language-python@0.45.4
├── language-ruby@0.71.3 (disabled)
├── language-ruby-on-rails@0.25.2 (disabled)
├── language-sass@0.61.1
├── language-shellscript@0.25.3 (disabled)
├── language-source@0.9.0 (disabled)
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.2
├── language-toml@0.18.1 (disabled)
├── language-typescript@0.2.1
├── language-xml@0.35.2
└── language-yaml@0.30.2

[36mCommunity Packages (95)[39m C:\Users\utilizador\.atom\packages
├── advanced-open-file@0.16.6
├── angularjs@0.4.0 (disabled)
├── artisan@0.3.1
├── atom-alignment@0.13.0
├── atom-beautify@0.30.5
├── atom-ctags@5.1.0
├── atom-ide-ui@0.4.0
├── atom-material-syntax-dark@1.0.0
├── atom-typescript@11.0.9
├── autoclose-html@0.23.0
├── autocomplete-corona@1.1.4 (disabled)
├── autocomplete-modules@1.7.0
├── autocomplete-paths@2.11.0
├── blade-snippets@0.2.0
├── busy-signal@1.4.3
├── caniuse@0.9.2
├── color-picker@2.2.5
├── data-atom@0.25.2
├── docblockr@0.11.0
├── editorconfig@2.2.2
├── emmet@2.4.3
├── expose@0.14.0
├── file-icons@2.1.12
├── filesize@3.0.0
├── flex-tool-bar@0.12.0
├── flow-ide@1.8.1 (disabled)
├── git-plus@7.9.3
├── goto-definition@1.3.4
├── highlight-selected@0.13.1
├── Hydrogen@1.23.0 (disabled)
├── hydrogen-launcher@1.2.1 (disabled)
├── hyperclick@0.1.5
├── ide-flowtype@0.17.4
├── ide-php@0.6.8
├── ide-typescript@0.6.1
├── increment-selection@0.3.0
├── intentions@1.1.5
├── language-blade@0.36.0
├── language-htaccess@0.1.1
├── language-log@1.8.0
├── language-lua@0.9.11 (disabled)
├── language-puppet@0.23.0 (disabled)
├── language-vue@0.23.1 (disabled)
├── laravel@0.7.1
├── less-than-slash@0.17.0
├── linter@2.2.0 (disabled)
├── linter-coffeelint@1.3.1 (disabled)
├── linter-csslint@2.0.0 (disabled)
├── linter-erb@1.1.0 (disabled)
├── linter-jshint@3.1.6 (disabled)
├── linter-jsonlint@1.3.0 (disabled)
├── linter-lsc@2.4.0 (disabled)
├── linter-luacheck@2.0.1 (disabled)
├── linter-markdown@5.2.0 (disabled)
├── linter-php@1.5.1 (disabled)
├── linter-puppet-lint@0.8.3 (disabled)
├── linter-sass-lint@1.8.0 (disabled)
├── linter-scss-lint@3.1.1 (disabled)
├── linter-tidy@2.3.1 (disabled)
├── linter-ui-default@1.6.10 (disabled)
├── livestyle-atom@0.2.10 (disabled)
├── local-history@4.3.0
├── minimap@4.29.7
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-highlight-selected@4.6.1
├── minimap-linter@2.1.1 (disabled)
├── minimap-pigments@0.2.2
├── minimap-selection@4.5.0
├── minimap-split-diff@0.3.7
├── notifications-plus@0.69.8
├── package-cop@0.2.10 (disabled)
├── pdf-view@0.59.0
├── php-getters-setters@0.5.5
├── pigments@0.40.2
├── platformio-ide-terminal@2.7.0
├── project-manager@3.3.5
├── quick-highlight@0.10.0
├── regex-railroad-diagram@0.19.4
├── Remote-FTP@1.1.3
├── rest-client@1.3.1
├── simple-drag-drop-text@0.3.4
├── sort-lines@0.15.0
├── split-diff@1.5.1
├── swap-selection@0.4.0
├── symbols-tree-view@0.14.0 (disabled)
├── sync-settings@0.8.3
├── tab-control@0.6.10
├── tasks@2.6.7
├── todo-show@2.0.0
├── toggle-quotes@1.0.1
├── toggler@0.3.0
├── tool-bar@1.1.0
└── wordcount@2.10.4

Update: it works fine when I deactivate this package

**Comment by evolutionmedia** [comment]
I have a similar issue. In my case autocomplete-html (and any other package) doesn't work at all in any kind of .php file, inside or outside php tags. Just disabling this plugin solves the issue.

**Comment by bboure** [comment]
I experience the same issue. autocomplete is not working at all.

**Comment by Azovsky** [comment]
I can not make it work either.

**Comment by rsese** [comment]
I started playing a bit with ide-php but don't have the same issue, auto-complete is working ok for me.  Can anyone share a specific example file with steps to reproduce within that file so I can give it a try?   Do any other features work for you (e.g. does the outline view work?) or is it just auto-complete not working?

**Comment by bboure** [comment]
@rsese the rests works ok. I will try to see how to reproduce, it might be another package that generates a conflict.
I use https://atom.io/packages/atom-autocomplete-php but of course I disabled it when I tried ide-php.
will keep looking.

**Comment by keevan** [comment]
It appears snippets created (snippets.cson) won't work if ide-php package is turned on, which is probably related.

**Comment by henres** [comment]
For what i see, snippets work, but not autocompletion. If i type: `fun`, the snippet fun work, but i don't have the autocompletion.

**Comment by litar1** [comment]
Hi all,

Unfortunately I have to confirm the issue on Ubuntu 16. The aoutocomplete feature is not working inside <?php ?> but works outside. Additionaly when atom core package autocomplete-html is disabled the problem is gone.

**Comment by kafoso** [comment]
![ide-php-useless-suggestions](https://user-images.githubusercontent.com/3169691/31770674-47707218-b4d9-11e7-936c-4b8ea5b7f9ab.png)

As this screenshot demonstrates, the suggestions are utterly useless and in no way resemble or relate to the method name I'm typing. I retried this multiple times at different typing speeds. Same result every time.

**Comment by Lazerproof** [comment]
The same thing here. 
Windows 10
Fresh install of Atom 1.22.0 x64.
After enabling of ide-php there is no autocomplete in php files at all.

**Comment by Nightbr** [comment]
related https://github.com/atom/ide-php/issues/78

**Comment by damieng** [comment]
Massive updates to the autocompletion lately - should now be filtering correctly and offers a priority setting so you can let snippets have higher priority.
