### ISSUE TITLE
Outline View not Displaying when using Ide-PHP

### ISSUE THREAD

**Issue by EricMcWinNer** [atom/ide-php#52]
I just installed the atom v1.21.0 Beta2 x64 and installed the PHP IDE language support. It's diagnostics and autocomplete are working (although they're really slow), but for some reason, I can't find the outline view panel on my program. I've gone through the package's settings and ensured the outline feature panel checkbox is checked, but I still don't see it on my software. Is it something I did wrong? Or is it disabled for PHP and allowed for other language supports?

EDIT
I installed IDE-Typescript, and it still doesn't show the outline panel, but the diagnostics is working. This problem obviously isn't peculiar to IDE-PHP. Does anyone have a solution?

**Comment by damieng** [comment]
Did you install the atom-ide-ui package ?

**Comment by EricMcWinNer** [comment]
Yes I did. I installed it and went through the options to make sure outline panel is enabled.
![screenshot 14](https://user-images.githubusercontent.com/19782345/31062683-6534139e-a724-11e7-8935-f1a574796c37.png)
![screenshot 15](https://user-images.githubusercontent.com/19782345/31062692-6a308d8c-a724-11e7-88e3-93afb05875e8.png)
![screenshot 17](https://user-images.githubusercontent.com/19782345/31062696-77050fc4-a724-11e7-9c78-17c5811761ae.png)

**Comment by damieng** [comment]
You should see an item in the View menu then called Toggle Outline View.

It is also a command you can access from the command palette -Outline View: Toggle

**Comment by damieng** [comment]
Once you have it open you should find it starts working for ide-typescript - ide-php does not support outline view yet.

**Comment by EricMcWinNer** [comment]
Thanks a lot damieng. You've solved my problem. I had no idea it'd be there.

**Comment by damieng** [comment]
Sorry, my mistake. Outline view is supported and should be working in ide-php.
