### ISSUE TITLE
Outline view and diagnostics stopped working after Atom beta 2 update

### ISSUE THREAD

**Issue by andrea-marcelli** [atom/ide-php#53]
Hi all,

As the title explains, the Outline view and diagnostics functionalities stopped working after Atom updated to the beta 2 pre release. Is it an issue with my system or should I just wait until development of the php-ide catches up? Should I consider downgrading?

Thank you

**Comment by damieng** [comment]
It should be working fine. 

Can you provide more information - do you get any errors?  Are the UI components still available?

Also can you check in the Atom dev tools window and see if there are any exceptions there.

**Comment by andrea-marcelli** [comment]
Hi damieng,

I don't get any error, just the same two windows than before, the only thing is that they are not functioning anymore. The Outline view simply states that php is not currently supported, which is strange, as it worked like a charme before

**Comment by damieng** [comment]
Can you check you still have ide-php installed?  Also please check the dev
tools windows for any errors.

**Comment by andrea-marcelli** [comment]
Yes, I have it installed. I also tried to run the application in devloper mode, inspecting the outline view, but I saw no errors whatsoever. That's odd

**Comment by damieng** [comment]
Okay, can you switch on detailed debugging?  You need to enter this in the dev tools console window from inside Atom then restart and try to open an PHP file.

`atom.config.set('core.debugLSP', true)`

**Comment by andrea-marcelli** [comment]
Hi, I switched on detailed debugging as per your request but no errors or warnings are showing up. Maybe I should just go with a clean install of Atom and its components

**Comment by andrea-marcelli** [comment]
I got it working by re-installing php-ide from scratch. In any case yhank you for your assistance damieng
