### ISSUE TITLE
Ide-php does not work

### ISSUE THREAD

**Issue by Desaydrone** [atom/ide-php#57]
I install Atom-ide and ide-php on Atom v1.21.0 but ide-php seems not working.

When i open the outline window show nothing, when i CTRL+ Click nothing

I'm on linux ubuntu 16.04
my php : 

`PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:25) ( NTS )
`
In dev mode after enable this : 

`atom.config.set('core.debugLSP', true)`

I got this error : 

`PHP (FelixFBecker) stderr Error: Call to undefined function AdvancedJsonRpc\json_decode() in /home/user/atom/.atom/packages/ide-php/vendor/felixfbecker/advanced-json-rpc/lib/Message.php:26
Stack trace:
#0 /home/user/atom/.atom/packages/ide-php/vendor/felixfbecker/language-server/src/ProtocolStreamReader.php(55): AdvancedJsonRpc\Message::parse('{"jsonrpc":"2.0...')
#1 /home/user/atom/.atom/packages/ide-php/vendor/sabre/event/lib/Loop/Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#2 /home/user/atom/.atom/packages/ide-php/vendor/sabre/event/lib/Loop/Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#3 /home/user/atom/.atom/packages/ide-php/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#4 /home/user/atom/.atom/packages/ide-php/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#5 /home/user/atom/.atom/packages/ide-php/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#6 {main}`

Php is well find : 

`HP (FelixFBecker) found PHP version 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 using "php"
logger.js:33 PHP (FelixFBecker) starting "php felixfbecker/language-server/bin/php-language-server.php --memory-limit=2G"
logger.js:33 PHP (FelixFBecker) rpc.sendRequest initialize sending `

I try ide-typescript and it works well

Did i miss something  ?

**Comment by damieng** [comment]
This looks like a problem with the underlying PHP language server itself - Can you report the error at https://github.com/felixfbecker/php-language-server and see if they have any ideas or solutions.

**Comment by Desaydrone** [comment]
Ok i do that,

Thanks for your response  :)

**Comment by jens1o** [comment]
That's actually a php binary error. You're missing the json extension, which is used by the Language Server Protocol. Apparently it is not included in your distro, which is very weird... :/

**Comment by Desaydrone** [comment]
I have to look that, i install the php7.1-json may be it's not active in the php.ini

**Comment by Desaydrone** [comment]
It woooorkkkkksss !!

in my 
`
/etc/php/7.1/cli/php.ini
`

Json wasn't enable, thanks for your help ! Now i can have fun with ide-php :+1:
