### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by 3Descape** [atom/ide-php#6]
![unbenannt](https://user-images.githubusercontent.com/5028761/30343871-433de348-97ff-11e7-9d02-ab61e0b05743.png)
Installation allways fails, even after deleting all installed packages insite the .atom/packages folder and admin rights. Used latest version 1.21.0-beta0 on win 10 x64 admin user. Composer is installed on this machine if this is important...

**Comment by damieng** [comment]
Hmm, it shouldn't need composer any more - I'll check that out.

If you do want to get running in the mean time you can open a command prompt to the ide-php folder and just type ```composer install``` which should setup the necessary language server and its dependencies.

**Comment by 3Descape** [comment]
thanks for quick support. I did the composer install and not much changed. The package shos as "PHP(FelixFBecker) started" but for example trying hyperclick shows the loading spinner and nothing happens. Same for formatting and basically all other tasks. I'm not sure if that is the atom-ide-ui package or this package though.

**Comment by Azovsky** [comment]
No possibility to install IDE-PHP:

![ide-php-install-bug](https://user-images.githubusercontent.com/417648/30346357-c95b1bae-9808-11e7-8a08-ee8f66788336.png)

Last Atom version is 1.20.0 (released this 3 hours ago).

**Comment by damieng** [comment]
@Azovsky Yes, as per the announcement this is for Atom beta only at this time.  https://atom.io/beta

**Comment by 3Descape** [comment]
Well there is the beta for version 1.21.. https://atom.io/beta

**Comment by Azovsky** [comment]
Thank you, @damieng , @3Descape ! It is working on Atom beta!

**Comment by UltimateBrent** [comment]
I had to navigate to the package directory and `composer install` to get it to work as well. Installing the language server myself elsewhere was complicated and ultimately ineffective anyway. Can you add the instruction to `composer install` to the readme? I think the issue is I didn't have PHP & Composer installed when I installed the plugin, so it didn't happen automatically, but there wasn't really any documentation on what to do after that.

**Comment by damieng** [comment]
You shouldn't need to do a `composer install` but it looks like the binary tar.gz version of the vendor folder I uploaded has some symlinks.  I'll try and get that fixed rather than reverting back to the composer install technique.

**Comment by damieng** [comment]
I've re-packaged the binaries - it looks like the symlinks from doing it on the Mac were messing things up.  New package will hopefully resolve that - if you update to 0.6.2 you should be good. Please raise a new issue if not!

**Comment by 3Descape** [comment]
I don't get any errors now, but still nothing appears.. no autocomplete, nothing..but this seems more like the atom-ide-ui package not working.. is there a way to test if it even installed correctly? should there be some entry in the packages dropdown or a command I could try running?
