### ISSUE TITLE
Var definition on comment

### ISSUE THREAD

**Issue by henres** [atom/ide-php#62]
Hello,
When i have definition of var in code comment, the autocompletion and hyperclick doesn't work.
```php
/** @var Response $myResponse */
$myResponse = $this->get('myproject.myresponse');
```
I can't hyperclick on Response or have autocompletion on $myResponse.

**Comment by henres** [comment]
Someone ?

**Comment by rsese** [comment]
Thanks for the report - can you share what version of Atom you're running and what operating system?  About the autocompletion, `$myreponse` autocompletes ok for me after creating a PHP file with your code snippet in macOS 10.12.6, Atom 1.24.0-dev-4f6e8ed5f, and php-ide 0.6.10.

**Comment by jens1o** [comment]
Long story short: https://github.com/felixfbecker/php-language-server/issues/350

This isn't implemented, yet.

**Comment by rsese** [comment]
Ahhh great, thanks for the pointer @jens1o :bow:  You can subscribe to the above issue if you'd like @henres.
