### ISSUE TITLE
IDE breaks when node_modules directory exists in project

### ISSUE THREAD

**Issue by ol1s** [atom/ide-php#64]
If I have a `node_modules` directory in the project root then this seems to kill the outline panel with an error message "No outline available - This is likely an error with the language package".

On further testing, this actually breaks all the IDE behaviour such as hyperclicking and intellisense.

If I remove the `node_modules` folder and reload ATOM then the IDE functionality works again.

As soon as I put the the `node_modules` folder back in project root then the outline panel breaks again.

**Comment by martinfojtik** [comment]
This is related to https://github.com/felixfbecker/php-language-server/issues/159
