### ISSUE TITLE
"PHP(FelixFBecker) started" message in status bar

### ISSUE THREAD

**Issue by niccolomineo** [atom/ide-php#69]
Hi, I am seeing the "PHP(FelixFBecker) started" message in the status bar. How can I get rid of it?

I have Atom 1.22 and ide-php 0.6.9.

Cheers.

**Comment by damieng** [comment]
Can you post a screen-shot?

**Comment by niccolomineo** [comment]
![schermata 2017-11-08 alle 09 29 29](https://user-images.githubusercontent.com/5409469/32539133-c05caaae-c468-11e7-8f3b-1a4a77f5a8d4.png)

**Comment by damieng** [comment]
Sorry, the confusion was this had been replace with a progress indicator but we hadn't yet published the updated version.  0.6.10 should now be available that will no longer include that part on the status bar.
