### ISSUE TITLE
Autocomplete class attributes & methods show more result than it should be

### ISSUE THREAD

**Issue by mmn6d6d6e** [atom/ide-php#70]
Hi. This is bugging me for a while.

![image](https://user-images.githubusercontent.com/19344000/32531357-e27a8cfc-c475-11e7-8a25-2c3f70636600.png)

But it run correctly when autocomplete variable & function outside class.
![image](https://user-images.githubusercontent.com/19344000/32531512-a4fe84cc-c476-11e7-92f8-bee366546493.png)

As a note, I tried on VSCode + PHPIntelliSense (which also using felixfbecker/php-language-server), and it run correctly.
![image](https://user-images.githubusercontent.com/19344000/32531564-03b8f9d4-c477-11e7-96e8-a98c8c56b350.png)

**Comment by vinkla** [comment]
I can confirm this issue as well. I'm running macOS 10.13.1 and Atom 1.22 with ide-php 0.6.9.

**Comment by VincentMarmiesse** [comment]
Confirmed also on Fedora 27, Atom 1.24.0 and ide-php 0.7.8

![capture d ecran de 2018-03-02 16-40-23](https://user-images.githubusercontent.com/1949412/36907251-7a00e8c0-1e38-11e8-818b-846699d3eeeb.png)

**Comment by damieng** [comment]
Should now be fixed - we always force filtering client side.
