### ISSUE TITLE
IDE-PHP language server stopped unexpectedly

### ISSUE THREAD

**Issue by nathan30** [atom/ide-php#72]
Hi,
I install the atom ide and the php-ide language and when I open a project, open a .php file the editor froze and force close. When I relaunch it I have the following error :

> PHP Warning: require(/home/nathan/.atom/packages/ide-php/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /home/nathan/.atom/packages/ide-php/vendor/composer/autoload_real.php on line 66 PHP Fatal error: require(): Failed opening required '/home/nathan/.atom/packages/ide-php/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/usr/share/php') in /home/nathan/.atom/packages/ide-php/vendor/composer/autoload_real.php on line 66

Did I miss something ?

Thanks in advance

**Comment by fkandus-olx** [comment]
I have a similar issue. The PHP IDE downloaded ok, then the editor crashed while unpacking and now I get the following when opening a .php file:

> PHP Warning: require(/home/dev/.atom/packages/ide-php/vendor/composer/../squizlabs/php_codesniffer/autoload.php): failed to open stream: No such file or directory in /home/dev/.atom/packages/ide-php/vendor/composer/autoload_real.php on line 66 PHP Fatal error: require(): Failed opening required '/home/dev/.atom/packages/ide-php/vendor/composer/../squizlabs/php_codesniffer/autoload.php' (include_path='.:/usr/share/php') in /home/dev/.atom/packages/ide-php/vendor/composer/autoload_real.php on line 66

**Comment by rsese** [comment]
Can both of you try updating ide-php to the latest version and see if that clears things up?

**Comment by fkandus-olx** [comment]
It's working for me now (version 0.7.1). Thanks!
