### ISSUE TITLE
Issue when encounters multiple Exception handling in a single statement

### ISSUE THREAD

**Issue by archindia** [atom/ide-php#76]
Says **'VariableName' expected** in diagnostics. Also expects "{" and ";" since it can judge that it is a single statement.

PHP Manual: [http://php.net/manual/en/language.exceptions.php](http://php.net/manual/en/language.exceptions.php)
```php
        try {
            throw new MyException();
        **} catch (MyException | MyOtherException $e) {**
            var_dump(get_class($e));
        }
```

**Comment by damieng** [comment]
As per the issue template;

`* What that server can do - syntax compatibility, whether it supports formatting or outlines etc - is outside of our control`

You'll need to file issues upstream with the technology that actually parses and understands the PHP - namely https://github.com/felixfbecker/php-language-server

**Comment by archindia** [comment]
Opps, thanks for point out the right project. 

Just for reference issue is already mentioned here: [https://github.com/Microsoft/tolerant-php-parser/issues/103](https://github.com/Microsoft/tolerant-php-parser/issues/103)
