### ISSUE TITLE
No autocomplete

### ISSUE THREAD

**Issue by cloudbluedigital** [atom/ide-php#78]
Hi guys, I have installed this package, however, I am having an issue with autocomplete. It does not show up at all I try to type `array` for example and I don't get anything `array_pu`, still nothing. Also, does it support importing use statements? Does it show if the variable is a string, int etc? Does it support formatting as user types? Sorry for so many questions but I just want to find out, exactly what is capable of. Thanks!

**Comment by Arcanemagus** [comment]
See https://github.com/facebook-atom/atom-ide-ui/issues/125#issuecomment-346414568 for the "format on type" question.

**Comment by wojlive** [comment]
Sure thanks for that. Awaiting for answer for other questions. On ide-ui it says when you hover over variable it shows what type of variable it is. Autocomplete sort of works, sometimes it shows up, sometimes it doesn't. But it still doesn't show up for stuff like array etc.

**Comment by cloudbluedigital** [comment]
Just a question, any ports or processes are running for autocomplete so I can whitelist them?? after disabling anti-virus it started working.

**Comment by damieng** [comment]
On Windows by default it uses sockets to communicate with the local language server so you might need to unblock php.exe for localhost (127.0.0.1)

**Comment by Nightbr** [comment]
autocomplete works but it is really slow... See my gif:

![autocomplete](https://user-images.githubusercontent.com/4228646/33371629-ae5c70b6-d4fb-11e7-9c07-981ac540d2f2.gif)

**Comment by Nightbr** [comment]
around 3-5seconds to display to autocomplete list from a known object

**Comment by Nightbr** [comment]
Related https://github.com/atom/ide-php/issues/10

**Comment by ricpelo** [comment]
Autocompletion is so slowly that's practically unusable. Is there a way to disable it temporarily without disable the whole package? Thanks.

**Comment by ctf0** [comment]
while the package is enabled, basically any php autocomplete won't work, the only solution so far seems to be disabling the ide-php package

**Comment by phh** [comment]
Any news here?

**Comment by jens1o** [comment]
see https://github.com/felixfbecker/php-language-server/pull/599 for improving speed of the autocompletion

**Comment by damieng** [comment]
Original issue was firewall rule, closing this issue.
