### ISSUE TITLE
0.7.1 is using old language-server

### ISSUE THREAD

**Issue by vinkla** [atom/ide-php#79]
When I download the latest version 0.7.1 I still get the old version of the `felixfbecker/language-serve` package. I've tried to reinstall the package multiple times but it still seems to download old Composer packages? I'm running Atom 1.22.1 and macOS 10.13.1 (17B48).

It seems it points to this archive [`php-ls-5.1.0.tar.gz`](https://github.com/atom/ide-php/files/1312302/php-ls-5.1.0.tar.gz) but it downloads this archive instead `php-ls-4.6.1.tar.gz`. Maybe it is cached on the fileserver?

**Comment by vinkla** [comment]
Fixed in bea5c6d7c498fd368aaecfe2399789f504b8fd6a.

**Comment by damieng** [comment]
Looks like the download url got messed up :(  0.7.2 is out with a corrected one.

**Comment by Ismail-elkorchi** [comment]
I'm getting the same error as @vinkla after updating ide-php to 0.7.2.

**Comment by damieng** [comment]
Yeah turns out the npm script to package the language server up created everything with an extra path in the archived structure because of differences between macOS and Windows.   (I was trying to get things fixed via my laptop, that'll teach me!)

0.7.3 resolves it.
