### ISSUE TITLE
PhP download

### ISSUE THREAD

**Issue by oxhey** [atom/ide-php#8]
Could someone link me to the correct php download.

I have tried the normal version and the windows version. Both dont work.

**Comment by 3Descape** [comment]
Did you specify the folder in the settings? and if you have sth. like xampp installed simply link to that php folder. in my example it would be C:\xampp\php\

**Comment by oxhey** [comment]
I dont have xampp installed. I downloaded the first link from this page http://php.net/downloads.php and extracted the folder to my c drive.

**Comment by damieng** [comment]
Open a command prompt and type `php --version` - if it displays something like 

```
PHP 7.1.4 (cli) (built: Apr 11 2017 19:54:37) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

Then you have PHP 7 correctly installed.

**Comment by oxhey** [comment]
I have now installed xampp. php --version still shows nothing.

**Comment by damieng** [comment]
I'm also on Windows and installed http://windows.php.net/download#php-7.1  the x64 thread-safe version (if you have a 32-bit version of Windows x86 would be needed).

**Comment by oxhey** [comment]
Fixed it. Needed to add php to windows environment variables

**Comment by damieng** [comment]
To PATH or to some other variables?

**Comment by oxhey** [comment]
PATH
