### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by dysback** [atom/ide-php#81]
OS: Win 10 x64
PHP: PHP 7.1.11 (cli) (built: Oct 25 2017 20:54:15) ( NTS MSVC14 (Visual C++ 2015) x64 )
Atom: 1.22.1 x64 (fresh installation)
atom-ide-ui: 0.6.0
ide-php: 0.7.3

Ide-php does not work at all.

**Comment by rsese** [comment]
Thanks for the report - can you share more details so we can take a look?  E.g. what exactly have you tried?  Are you having trouble with any PHP files or just particular files (can you share an example file)?

If you can share exactly what you're seeing with screenshots or GIF/screencast, that could be helpful. 

Lastly, please let us know if you see any errors in developer tools:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools

**Comment by dysback** [comment]
I can't see any error. PHP is in windows path and works from any location. There is no any IDE functionality in in any PHP file.

![atom](https://user-images.githubusercontent.com/1359937/33595822-d5ffab54-d999-11e7-9856-bfb31d662eb3.png)
![atom](https://user-images.githubusercontent.com/1359937/33595911-21fe2ddc-d99a-11e7-9a89-f0520221c79b.png)

Thanks for support

**Comment by 50Wliu** [comment]
You need to mark your file as PHP.  Open the Grammar Selector (Ctrl+Shift+L) and click Auto Detect.
