### ISSUE TITLE
Autocomplete for HTML within PHP

### ISSUE THREAD

**Issue by tallon1252** [atom/ide-php#82]
When i edit HTML inside PHP files, every autocomplete suggestion gives me first the <?php tag, not the HTML tag like i would expect.

Is this a bug or a feature?

**Comment by vinkla** [comment]
This is duplicate of #47.

**Comment by rsese** [comment]
Thanks @vinkla :bow:

Closing as a duplicate of https://github.com/atom/ide-php/issues/47 where this issue is being investigated, you can subscribe there for updates if you'd like @tallon1252.
