### ISSUE TITLE
Disable autocompletion only for this package

### ISSUE THREAD

**Issue by ricpelo** [atom/ide-php#83]
Hi!

Can I disable autocompletion only for ide-php suggestions? So autocomplete-plus still works for other packages, but not for this one.

Sorry if this is the wrong place to ask this question, because I don't know if it's a matter of ide-php or atom-ide-ui.

Thanks in advance.

**Comment by rsese** [comment]
Hmm, I don't believe that's possible on the ide packages side of things but you can add `*.php` to `Settings > Packages > autocomplete-plus > Files Blacklist` and that should prevent suggestions from popping up in PHP files.
