### ISSUE TITLE
Update felixfbecker/language-server up to v5.1.2

### ISSUE THREAD

**Issue by ricpelo** [atom/ide-php#84]
`felixfbecker/language-server` v5.1.2 was released a day ago:

https://github.com/felixfbecker/php-language-server/releases

It contains some great improvements over the 5.1.0 (the version that `ide-php` is installing now according to `composer.lock` file):

https://github.com/atom/ide-php/blob/58a02fcb8f6bfdb7e47b277bad47f7cc502c9530/composer.lock#L311

Thanks in advance!

**Comment by developer-lindner** [comment]
It's already v5.2.0 ;)
