### ISSUE TITLE
Debug workflow: Should I use php-debug alongside ide-php?

### ISSUE THREAD

**Issue by michaelmcandrew** [atom/ide-php#87]
Hi there,

I understand that xdebug should not be enabled when running php-language-server as it has a big impact on performance. At the same time, I do want to use xdebug for debugging and I have been using https://atom.io/packages/php-debug for this until now.

So my questions are:

1) Is there an elegant way to disable xdebug for php-language-server but have it enabled for other processes? I'm guessing that some combination of `php --php-ini [blah]`, aliasing php, and maybe using the `PHP_INI_SCAN_DIR` environment variable will do it but I am yet to find a simple / elegant solution. I thought maybe someone has already solved the problem.

2) Is using php-debug alongside ide-php the best approach to debugging at the moment? I see that integrating a debugger is on the atom-ide-ui https://nuclide.io/blog/2017/09/12/Introducing-Atom-IDE-UI/#roadmap but not sure when that will land and am wondering what to do in the mean time.

PS. Great work - enjoying it so far :+1:

**Comment by damieng** [comment]
I do not have any experience with xdebug or php-debug packages so can not advise on how best to use it with this package, sorry.

**Comment by michaelmcandrew** [comment]
OK, thanks anyway!
