### ISSUE TITLE
Package breaks after every Atom Update

### ISSUE THREAD

**Issue by Syphdias** [atom/ide-php#88]
Every time I update Atom, I need to reinstall the package. Currently, I am already at the latest Atom Beta (1.24.0-beta0) on Windows 10  
Since I already reinstalled ide-php, I can't check for these errors anymore:
* "disconnected", "JSONRPC" or "Content-Header" errors indicate that server process died. 

What I can tell you is, that the green icon in the packages list disappears when it happens. There is no message of any sort that I saw. The functionality just disappears.  
Another Information which could be helpful is that I use the Bitdefender ransom protection. Which makes me add Atom to the trusted Applications again (I guess because he binary changes every time and it's not signed). I can't tell if this could be the reason. I will turn it off for the next update so I can check if this is the reason and come back to you.

**Comment by damieng** [comment]
You might want to exclude your Atom folder `c:\users\yourname\appdata\local\atom` and see if that helps.  The Atom binary is digitally signed - there's not much else we can do to placate aggressive AV heuristics.

An exact error message and sequence might be helpful next time.

**Comment by Syphdias** [comment]
If you mean to exclude the folder from being watched, it is not being watched by the AV. If you mean to include every binary in the folder to the accepted binaries. That's not possible as far as I can tell, there's no recursive adding of binaries.

I'll provide you with more information as soon as a new Atom update comes out since this seems to be the initial cause.

I could send you some errors I get while completion, but I don't think that's related. I might open another issue for that.

**Comment by Syphdias** [comment]
If there is anything I can provide, like an install log or something, please let me know.

**Comment by Syphdias** [comment]
I tried to reproduce it a couple of times now, with and without AV, and couldn't.
I can only guess what could have caused the problem. Maybe some other broken package which got fixed by now.

**Comment by damieng** [comment]
Okay, going to close this issue. Feel free to comment here if it re-occurs and we'll re-open.
