### ISSUE TITLE
this package break the order of autocomplete

### ISSUE THREAD

**Issue by yanggs07** [atom/ide-php#95]
when autocomplete with no plugin,
the `fun` snippet in atom usually be
```php
public function FunctionName($value='')
    {
        # code...
    }
```
but with ide-php and other complete plugin:
![image](https://user-images.githubusercontent.com/13307027/34513711-92f7c0ae-f0a4-11e7-83df-1ff7bab0ce84.png)
the order changed and the most used `fun` no longer be the first

can i disable autocomplete by ide-php?

thanks.

**Comment by damieng** [comment]
Latest version has configuration settings letting you choose the priority of ide-php's autocomplete.
