### ISSUE TITLE
Go to definition does not work

### ISSUE THREAD

**Issue by atefBB** [atom/ide-php#98]
When I click `ctrl-mouse-left-button` to go to PHP `class`/function` definition, the package does not `go to definition`! 
I'm using this package on Windows 7 with PHP7 installed.
Did I miss something?

**Comment by rsese** [comment]
Can you share an example file where this doesn't work for you so we can take a look?

**Comment by zatch** [comment]
I think I'm having the same issue. I can give some details, but the files I'm working with aren't mine to share (and I'm a PHP noob, so I don't think I have the chops to set up a separate demo of the issue).

I'm not sure how helpful this is, but here's what I'm experiencing... Let me know if I can provide additional information.

# Sample class `test`:
```
<?php
class test extends unicore{
    function init(){
        parent::uni('framename');
        $this->uni->hook('main_hook','test',['variable'=>'new Component']);
        $this->uni->include_js_var();
        $this->uni->output();
    }
}
```
### Observations from class `test`:
My class `test` extends `unicore`, which is defined in ../../_neoan/base/core.php (relative to my test.php file)

On line 2: ctrl+click on `unicore` works perfectly, taking me to the proper class definition in core.php

On line 4: ctrl+click on `parent` also takes me to the `unicore` definition in core.php, which seems desired

`unicore` class has a function `uni`, but ctrl+click `uni` does not work anywhere (lines 4, 5, 6, 7)

ctrl+click also doesn't work on functions of `$this->uni`, which I guess makes sense, considering it can't understand `$this->uni` to begin with (referring to functions `hook`, `include_js_var`, and `output` on lines 5, 6, 7)

# Parent class `unicore`:
```
class unicore{
    function uni($frame, $add=''){
        $this->uni = new layout($frame,$add);
        $track = debug_backtrace();
    }
...
```
### Observations from class `unicore` (in core.php):

On line 3: ctrl+click `layout` works perfectly, taking me to the proper definition in the proper file (../layout/index.output.php, relative to core.php)

`layout` has functions `hook`, `include_js_var`, and `output`, which are the relevant functions I tried to ctrl+click in my `test` class above

**Comment by atefBB** [comment]
take this example (from a laravel project):
`<?php`
` Route::get('/users', function() { `
   `return User::all(); `
`});`
when I tried `click-ctrl` in `Route` class it's should go to the definition but it doesnot ! same in the case of `User` class !

**Comment by mirorauhala** [comment]
@atefBB maybe it's that the routes.php file in Laravel doesn't contain the keyword 

```php
use Illuminate\Support\Facades\Route
``` 

So the plugin doesn't know where Route is defined. **You don't need to add the use keyword as it is called in RouteServiceProvider.** `ide-php` just doesn't know how to call your RouteServiceProvider before the routes file to get the Route facade.

In some cases (especially in a git project), you need to untick Atom Settings > Core > Exclude VCS Ignored Paths.

**Comment by bourdeau** [comment]
Same problem here even with unticked "Exclude VCS"

```php
        $queryPart = new Query\BoolQuery();

        $queryPart->addMust((new Query\MultiMatch())
                  ->setFields(self::STAT_ACTION)
                  ->setType('phrase')
                  ->setQuery($options['action'])
                  ->setParam('boost', 2)
              );
```
If I hover ``->addMust`` and hold ``Ctrl`` key the cursor keep spinning endlessly. And if I click to Go To Declaration nothing happens.

:(

**Comment by rgazelot** [comment]
Any updates? This feature still doesn't work for me.

**Comment by rgazelot** [comment]
I think that answer the question

**Comment by MatTheCat** [comment]
Encountered this issue; root cause was https://github.com/felixfbecker/php-language-server/issues/462
